### ISSUE TITLE
Add AttractMode to portable?

### ISSUE THREAD

**Issue by IceLancerSR** [Akiafroo/Retroshur#1]
Add AttractMode to portable?
Can you?

**Comment by Akiafroo** [comment]
yes its posible. maybe in one or two weeks im going to update the pack. i have already installed in my local machine but its to heavy right now 1gb just attract-mode.

**Comment by IceLancerSR** [comment]
I tried calling ur .cmd for rocketlauncher via command its works but it ignores core and load some random i cant figure out why

args                 mame "[name]" fbalpha2012_libretro.dll
core is being ignored it just loads mame and mame first core for it.U have proper cmd function to fix it?
